name : CI/CD
on : push

jobs :
  CI-CD :
    name : Lint code base
    runs-on : ubuntu-latest
    steps :
        #Primo step
      - name : Checkout code
        uses : actions/checkout@v2
      
        #Secondo step: avvio container
      - name: Start containers 
        run: docker-compose up -d --build
        
        #Terzo step
      - name: Waiting for containers 
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
